import * as THREE from "three";
const textureLoader = new THREE.TextureLoader();
export const matCap1 = textureLoader.load("/textures/matcaps/matcap_1.jpg");
export const matCap2 = textureLoader.load("/textures/matcaps/matcap_2.jpg");
export const matCap3 = textureLoader.load("/textures/matcaps/matcap_3.jpg");
export const matCap4 = textureLoader.load("/textures/matcaps/matcap_4.jpg");
export const matCap5 = textureLoader.load("/textures/matcaps/matcap_5.jpg");
export const matCap6 = textureLoader.load("/textures/matcaps/matcap_6.jpg");
export const matCap7 = textureLoader.load("/textures/matcaps/matcap_7.jpg");
export const matCap8 = textureLoader.load("/textures/matcaps/matcap_8.jpg");
