/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 JNL.glb --transform
Files: JNL.glb [1.27MB] > /Users/whp/Desktop/JNL/JNL Blender/Exports/JNL-transformed.glb [85.73KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function JNL(props) {
  const { nodes, materials } = useGLTF("/models/JNL-transformed.glb");
  console.log(nodes);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Loft_Handrails_02.geometry}
        // material={nodes.Loft_Handrails_02.material}
        rotation={[0, Math.PI / 2, 0]}
        position={[0, -1, 0]}
      >
        <meshStandardMaterial />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/JNL-transformed.glb");
