/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 JNL_04.glb --transform
Files: JNL_04.glb [189.66KB] > /Users/whp/Documents/HTML/WHP WEBSITE ROOT/ASSETS/JNL/JNL Blender/Exports/JNL_04-transformed.glb [79.14KB] (58%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import InvisibleWalls from "./InvisibleWalls";
import { matCap2 } from "../modules/matcapMats";

export default function JNL2(props) {
  const { nodes, materials } = useGLTF("/models/JNL_04-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <InvisibleWalls />
      <mesh geometry={nodes.Loft_Handrails.geometry} position={[0, -1, 0]}>
        <meshMatcapMaterial matcap={matCap2} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/JNL_04-transformed.glb");
