/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Suzanne.glb --transform 
Files: Suzanne.glb [356.38KB] > /Users/whp/Documents/HTML/whp-website-2024/public/models/Suzanne-transformed.glb [51.71KB] (85%)
*/
import { useGLTF } from '@react-three/drei'

export function Suzanne(props) {
  const { nodes, materials } = useGLTF('/models/Suzanne-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Suzanne.geometry} material={nodes.Suzanne.materials} />
    </group>
  )
}

useGLTF.preload('/models/Suzanne-transformed.glb')
